# This is a basic workflow to help you get started with Actions

name: Install and test setup

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ninja-build \
            gettext \
            cmake \
            unzip \
            curl \
            python3 \
            python3-pip \
            clang-format \
            ripgrep \
            fd-find \
            npm \
            git
            # Install python<version>-venv
            # Some language server do create a python3-venv  (e.g. the LSP for CMake)
            sudo apt-get install -y $(readlink $(which python3))-venv python3-neovim

            git clone https://github.com/neovim/neovim
            cd neovim
            git checkout v0.10.1
            make CMAKE_BUILD_TYPE=RelWithDebInfo -j16
            sudo make install
            cd .. 
            rm -rf neovim

            git clone --depth 1 https://github.com/wbthomason/packer.nvim \
            ~/.local/share/nvim/site/pack/packer/start/packer.nvim

            # Run PackerSync to install required packages
            nvim -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

            # Install oh-my-zsh
            apt-get install -y zsh
            sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
